const currencies = {
    MSG: 'Select a currency',
       USD: 'United States Dollar',
       AUD: 'Australian Dollar',
       BGN: 'Bulgarian Lev',
       BRL: 'Brazilian Real',
       CAD: 'Canadian Dollar',
       CHF: 'Swiss Franc',
       CNY: 'Chinese Yuan',
       CZK: 'Czech Republic Koruna',
       DKK: 'Danish Krone',
       GBP: 'British Pound Sterling',
       HKD: 'Hong Kong Dollar',
       HRK: 'Croatian Kuna',
       HUF: 'Hungarian Forint',
       IDR: 'Indonesian Rupiah',
       ILS: 'Israeli New Sheqel',
       INR: 'Indian Rupee',
       JPY: 'Japanese Yen',
       KRW: 'South Korean Won',
       MXN: 'Mexican Peso',
       MYR: 'Malaysian Ringgit',
       NOK: 'Norwegian Krone',
       NZD: 'New Zealand Dollar',
       PHP: 'Philippine Peso',
       PLN: 'Polish Zloty',
       RON: 'Romanian Leu',
       RUB: 'Russian Ruble',
       SEK: 'Swedish Krona',
       SGD: 'Singapore Dollar',
       THB: 'Thai Baht',
       TRY: 'Turkish Lira',
       ZAR: 'South African Rand',
       EUR: 'Euro',
   };
   const fromCurrency = document.getElementById("button-1");
   const toCurrency = document.getElementById("button-2");
   fromCurrency.innerHTML = getOptions(currencies);
   twoCurrency.innerHTML = getOptions(currencies);